### ISSUE TITLE
Initial version

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBayes.jl#1]
@xukai92 created this notebook:

http://nbviewer.jupyter.org/github/xukai92/TuringDemo/blob/master/Differential%20Equation/turing-de.jl.ipynb

This is essentially a prototype of what we'd like to have. I am thinking of something like:

```julia
bayesian_de_estimation(prob::DEProblem,alg,priors,likelihood;kwargs...)
```

`priors` would be a tuple of priors, one for each parameter in `p`. I.e. it should match `num_params(prob.f)`. `likelihood` would be a function for calculating the likelihood from each result, like: `(res,σ)->MvNormal(res, σ*ones(length(σ))`. This can be an optional argument since that's by far the most standard choice.

Then it would do something like:

```julia
@model bfit(x) = begin
    # Define priors?
    a ~ Truncated(Normal(1.5, 1), 0.5, 2.5)  # DE param
    σ ~ InverseGamma(2, 3)               # data noise

    # Update solver
    p_tmp = problem_new_parameters(prob, a); sol_tmp = solve(p_tmp,Tsit5())

    # Observe data
    # Here you can do a lot of ways to write the observation
    # and a lot of possible optimization to make the program faster
    # E.g. naively

    for i = 1:length(t)
        res = sol_tmp(t[i])
        x[:,i] ~ likelihood(res, σ)
    end
end
```

which would match the notebook's. I'm not entirely sure how to do things like the prior and all of that because of the macro interface.

@xukai92 can you help get the first version together?

**Comment by xukai92** [comment]
Sorry for my slow response, due to my home holiday recently.

Sure - I guess a single `.jl` file with everything in function will be fine for a prototype purpose. I will do this along with comments & doc (https://github.com/yebai/Turing.jl/issues/336). Once both of us understand everything, we can move forward from there. Does this sound good?

**Comment by ChrisRackauckas** [comment]
Yeah, that sounds great!

**Comment by xukai92** [comment]
I've created a macro free version of the notebook here (https://github.com/xukai92/DiffEqBayes.jl/blob/turing-init/src/turing_macro_free.jl). I still call Turing.jl's `@model` once with empty body to initialise some meta-info inside Turing.jl (L31-L33). Besides that removing the `@model` macro is simply creating a function with specific (keyword) arguments and return `vi` in the end.

**Comment by ChrisRackauckas** [comment]
Nice! That's looking very close to what we need. Two points to mention:

1. `σ ~ InverseGamma(2, 3)` that's only going to parse on v0.5. What do you guys plan on doing for v0.6 when `~` is no longer a macro?

2. `a ~ Truncated(Normal(1.5, 1), 0.5, 2.5)`. If you take a look at what we did with Stan (https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/test/runtests.jl#L17) the user just passes an array of priors. Is there a way that this can be automatically expanded to an array of `a`s? 

I think that if those two points are addressed we'll have something that can pretty much match the `bayesian_inference` interface of Stan.

**Comment by xukai92** [comment]
For 1, I'm not quite sure what's Hong's plan on it as I'm current away. But actually I can further remove the `~` notation (i.e. just use function)
For 2, it's possible with `~` notation but tricky. Similar to 1, let me just also remove the `~` notation, which will be easier to work with.

**Comment by ChrisRackauckas** [comment]
>let me just also remove the ~ notation, which will be easier to work with.

I think that's a good idea. For this purpose, it's all backend and not user-facing code so it doesn't have to look particularly nice as long as it's well documented.

**Comment by xukai92** [comment]
I updated the script (commit=7134fca6108c9ce2d16b078bd10667830c9ca83d). 

Also with `~` removed, the meta-info initialisation lines are no longer needed.

**Comment by ChrisRackauckas** [comment]
Looks great! I think we just have to think about (2) then. If you were just given an array of priors, how would you generate the code and the names? Do you think using Base.Cartesian is a good fit for this, or do you have something for arrays of priors already?

**Comment by ChrisRackauckas** [comment]
```julia
    a = Turing.assume(sampler,
                      Truncated(Normal(1.5, 1), 0.5, 2.5),
                      Turing.VarName(vi, [:bif, :a], ""),
                      vi)
```

is the `a = ` part even necessary there? It seems like it's not used? Would just doing

```julia
Turing.assume(sampler,
                      Truncated(Normal(1.5, 1), 0.5, 2.5),
                      Turing.VarName(vi, [:bif, :a], ""),
                      vi)
```

work? If so, then if we had an array of priors, we can just do

```julia
for i in 1:length(priors)
  Turing.assume(sampler,
                      priors[i],
                      Turing.VarName(vi, [:bif, :theta$i], ""),
                      vi)
end
```

**Comment by xukai92** [comment]
I'm not familiar with Base.Cartesian. 

Yes `a = ` is necessary because we actually will use the normal Julia variable `a`. I think in your example we can simply do

```julia
N = length(priors)
theta = Array(N)
for i in 1:length(priors)
  theta[i] = Turing.assume(sampler,
                      priors[i],
                      Turing.VarName(vi, [:bif, :theta$i], ""),
                      vi)
end
```

**Comment by ChrisRackauckas** [comment]
Thanks. With this help I completed the `turing_inference` function that does exactly this. It doesn't work on v0.6 though since Turing.jl isn't v0.6-compatible, so its tests are disabled. But it's all setup and can be iteratively improved in the future. Thanks!
