### ISSUE TITLE
Remove Mamba dependency

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaDiffEq/DiffEqBayes.jl#132]
Since #127 Mamba is no longer used, and the only place in the code-base [where I found it](https://github.com/JuliaDiffEq/DiffEqBayes.jl/search?q=Mamba&unscoped_q=Mamba) is in the stan_inference.jl [plotting functions](https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/afac88fd7f1bfbfee2cc8bf9dbfbb915b420b034/src/stan_inference.jl#L144-L153).

If the Mamba dependency is removed, I think https://github.com/JuliaDiffEq/DiffEqTutorials.jl/issues/129 could be more easily solved since Mamba is the only one (in DiffEqTutorials) that depends on Gadfly.

I can make a PR if you agree.

**Comment by ChrisRackauckas** [comment]
I agree: let's isolate or get rid of this. No brainer: it's tough to install.

**Comment by SebastianM-C** [comment]
Stan.jl seems to support plotting via StatsPlots: https://github.com/StanJulia/Stan.jl/blob/eb695d35966ea75d0e8e7ba4f176b7e2d771a093/Examples/Bernoulli/bernoulli.jl
Should I remove the `get_plot_object((bayesian_result::StanModel)` and `plot_chain(bayesian_result::StanModel,filename=nothing)` methods?

**Comment by ChrisRackauckas** [comment]
Yes please. BTW, Stan.jl was deprecated for CmdStan.jl IIRC.
