### ISSUE TITLE
Integrate with Stan.jl

### ISSUE THREAD

**Issue by Ayush-iitkgp** [JuliaDiffEq/DiffEqBayes.jl#2]
All the Bayesian techniques from different libraries such as Stan and Turing will be implemented here. 
Moving the issue [Link with Stan.jl](https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/issues/3) here. 
@ChrisRackauckas please update the introduction about of the package :)

**Comment by ChrisRackauckas** [comment]
Looks like we're in the game. Next issues will be more specific.
