### ISSUE TITLE
Trying your example

### ISSUE THREAD

**Issue by goedman** [JuliaDiffEq/DiffEqBayes.jl#4]
Hi @Ayush-iitkgp 

I'm trying your example to figure out the filtering issue but where is bayesian_inference coming from?

Rob

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBayes.jl/pull/3

**Comment by goedman** [comment]
julia> sim=bayesian_result.chain_results
Object of type "Mamba.Chains"

Iterations = 1:1
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1

[-83.601 0.0 … 0.96472 -1.73374]

[-46.9753 0.0 … 5.07664 -0.439044]

[-32.9746 0.0 … 1.9575 0.511501]

[-44.2234 0.0 … 7.73749 0.510299]

julia> fieldnames(sim)
4-element Array{Symbol,1}:
 :value 
 :range 
 :names 
 :chains

julia> sim.names
10-element Array{AbstractString,1}:
 "lp__"         
 "accept_stat__"
 "stepsize__"   
 "treedepth__"  
 "n_leapfrog__" 
 "divergent__"  
 "energy__"     
 "sigma.1"      
 "sigma.2"      
 "theta.1"      

julia> sim[1:10, ["theta.1", "sigma.1"],:]
Object of type "Mamba.Chains"

Iterations = 1:1
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1

[-1.73374 1.10297]

[-0.439044 1.91719]

[0.511501 1.52393]

[0.510299 3.86279]

**Comment by goedman** [comment]
I noticed you had it solved, but just for future reference. I really like the bayesian_inference() setup!
