### ISSUE TITLE
Change default sampling algorithm to NUTS for Turing.jl

### ISSUE THREAD

**Issue by xukai92** [JuliaDiffEq/DiffEqBayes.jl#49]
The NUTS sampler in Turing.jl is more stable now. It might be good for us to make it as default (which is what Stan does) so that user doesn't need to set step size and step numbers manually.

**Comment by xukai92** [comment]
Simply change https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/src/turing_inference.jl#L45 to

```julia
chn = sample(bif, Turing.NUTS(num_samples, delta))
```

and the function definition at https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/src/turing_inference.jl#L1-L2 to

```julia
function turing_inference(prob::DEProblem,alg,t,data,priors = nothing;
                            num_samples=1000, delta=0.65, kwargs...)
```

**Comment by xukai92** [comment]
It's one of the basic sampler you can use (https://github.com/TuringLang/Turing.jl/wiki/Get-started#basics). I can take care of this change and submit a PR very soon.

**Comment by ChrisRackauckas** [comment]
Cool, thanks!
