### ISSUE TITLE
Analysis tooling

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBayes.jl#5]
It looks like both Stan and Turing are going to be returning Mamba chains. Since we're controlling the naming and the input, we should be able to build common tooling for these. Plotting of the chain values over iterations and the distribution plots are two things that we should definitely have easily accessible.

**Comment by ChrisRackauckas** [comment]
`plot_chain` for Stan.jl is implemented. Will it work for Turing.jl and DynamicHMC.jl as well @Vaibhavdixit02 ?

**Comment by Vaibhavdixit02** [comment]
Currently I was using the `StanODEModel` type as the type constraint on passing the result to the function but it can be easily extended for Turing.jl too as it essentially returns Mamba chains too but I am not sure how to handle DynamicHMC.jl yet, would be clearer once we gave the wrapper set up I think.
