### ISSUE TITLE
More priors

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBayes.jl#6]
We should be able to specify more priors. We just need to define a dictionary that says how to convert Distributions.jl distribution types to strings that Stan can use. @goedman is there a list of Stan distributions somewhere?

And we might need to special case truncations of distributions using the information from http://discourse.mc-stan.org/t/estimating-the-parameters-of-the-differential-equations-using-stan/1663

**Comment by goedman** [comment]
Not so much a list, but chapters 8 and 9 in the language reference manual contains the info 

http://mc-stan.org/users

**Comment by ChrisRackauckas** [comment]
@Ayush-iitkgp do you have a script that shows the truncations working? That would be helpful.

Also, we should try the Lotka-Volterra problem using strictly positive priors. That's probably a better way to handle it.

**Comment by ChrisRackauckas** [comment]
For those looking to implement this, right now we have it hard-coded for normal distributions:

https://github.com/JuliaDiffEq/DiffEqBayes.jl/blob/master/src/stan_inference.jl#L24

What would be needed is to refactor this as a `stan_string(::Normal)` which generates that string, and then add a bunch of other dispatches using the Stan manual and the Distributions manual to find out how to translate them.

**Comment by ChrisRackauckas** [comment]
Completed by https://github.com/JuliaDiffEq/DiffEqBayes.jl/pull/17
