### ISSUE TITLE
Adding of DiffEqBayes package fails with an error on Julia 1.0.2 both on linux and windows. 

### ISSUE THREAD

**Issue by buriom** [JuliaDiffEq/DiffEqBayes.jl#61]

**Comment by buriom** [comment]
ERROR: Unsatisfiable requirements detected for package DiffEqBayes [ebbdde9d]:
 DiffEqBayes [ebbdde9d] log:
 ├─possible versions are: [0.0.1, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by ChrisRackauckas** [comment]
It just needed a tag. The new released version should work.

**Comment by buriom** [comment]
Hello Chris, the version I am using is the one released on 2018-11-08, should I expect any newer version soon? Thanks

**Comment by ChrisRackauckas** [comment]
I just released one 6 hours ago

**Comment by buriom** [comment]
Could you kindly guide me on how to incorporate the new changes (I just started using Julia after epirecipes haven't yet grasped package management). Should I just use Pkg.add("DiffEqBayes") or do I need to download the whole repo and reinstall Julia 1.0.2

**Comment by ChrisRackauckas** [comment]
Use ]up

**Comment by buriom** [comment]
Dear Chris, ] up did update the new DiffEqBayes module (only on linux) but trying to add it still produces the error.

**Comment by ChrisRackauckas** [comment]
did you get v0.7.0?
