### ISSUE TITLE
Adding of DiffEqBayes package fails again with an error on Julia 1.0.2

### ISSUE THREAD

**Issue by zimmermm** [JuliaDiffEq/DiffEqBayes.jl#62]
This is similar to #61 but this time the error is:
``
ERROR: Unsatisfiable requirements detected for package DiffWrappers [87bc27b3]:
 DiffWrappers [87bc27b3] log:
 ├─possible versions are: 0.0.1 or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with DiffEqBayes [ebbdde9d] to versions: 0.0.1 — no versions left
   └─DiffEqBayes [ebbdde9d] log:
     ├─possible versions are: [0.0.1, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.7.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0-0.6.1, 0.7.0]
     └─restricted by julia compatibility requirements to versions: 0.7.0 or uninstalled, leaving only versions: 0.7.0
``

**Comment by ChrisRackauckas** [comment]
Yeah interesting: it doesn't serve you v0.7.0 with that?

**Comment by ChrisRackauckas** [comment]
Okay, we will have another release coming out soon which fixes a few things. Most of the work was in https://github.com/JuliaDiffEq/DiffEqBayes.jl/pull/60 but we're going to have to release without DynamicHMC since it's taking too long.

**Comment by Vaibhavdixit02** [comment]
@zimmermm we have had a new release that should fix the issue, let us know if you face any other issues!
