### ISSUE TITLE
Likelihood choices and Hyperparameters

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBayes.jl#7]
We need some way for a user to pass a choice of likelihood, along with the hyperparameters for it.

**Comment by ChrisRackauckas** [comment]
Completed for Stan by @Vaibhavdixit02

**Comment by ChrisRackauckas** [comment]
Is this possible with Turing and DynamicHMC @Vaibhavdixit02 ?

**Comment by Vaibhavdixit02** [comment]
I think Turing and DynamicHMC already support all Distributions.jl distributions?

**Comment by ChrisRackauckas** [comment]
Oh for the likelihoods and some hyperparameters?

**Comment by Vaibhavdixit02** [comment]
I'll have to check for the hyperparameters, for the likelihood yes. Will get back to you regarding hyperparameters.
